### ISSUE TITLE
Any new release planned

### ISSUE THREAD

**Issue by silviucpp** [fogfish/esq#1]
Hello,

I see master if behind the other branch. any release planned with on-disk-overflow ?

**Comment by fogfish** [comment]
Hello,

Thank you for comments! Let me elaborate the status.

I've kicked off the project to support various storage backends (main branch): in-memory, raw binary file, text file and dets. The usage of the project under various live scenarios made me think that variety of backends complicates the project. I've used the raw binary file in my applications. The on-disk-overflow branch forgets other backends and made a queue to always overflow on the disk using raw file. I've found these approach usable and it simplifies the whole solution.

I'll be glad to promote on-disk-overflow branch to the master and make release out of it (e.g. during this week). Personally, I see a little value to support multiple storage backends. However, I'd like to get your feedback on this matter. Do you need a support for multiple backends?

**Comment by silviucpp** [comment]
Hello,

No I don't need :) I agree with you that one backend for in memory and one for disk storage it's enough.. and better focus on improve those instead adding more backends

Thanks,
Silviu

**Comment by silviucpp** [comment]
For example a functionality that will be nice it's to add methods for:

peek - return the head but don't remove it from queue (queue is not changed in any way)
size - returns how many items are in queue

Silviu

**Comment by silviucpp** [comment]
One more tip :  acknowledge message by clients should be better documented, In this moment you need to read the code carefully to understand when it's used and how.

**Comment by fogfish** [comment]
a new release is assembled with strong focus on documentation.
