### ISSUE TITLE
Project is not longer compile with rebar. works only via rebar3

### ISSUE THREAD

**Issue by silviucpp** [fogfish/esq#11]
Lot of libraries still keeps compatibility. Build is broken because in rebar you can't set as deps like: datum without specifying the github url and tag. 

Silviu

**Comment by fogfish** [comment]
It does not sounds good! Let me think what I can do. BTW, What is your motivation to use `rebar`?

**Comment by silviucpp** [comment]
Hello,
Lot of ancient projects still uses rebar. You can see here: https://github.com/benoitc/hackney/blob/master/rebar.config.script on how other libraries handles this to keep compatible with both

**Comment by fogfish** [comment]
Yeah, I do see that some libraries keeps the compatibility. I am trying to understand your reason of still using rebar?
* Is you library depends on this library and you want to support both version of rebar?
* You are using this library within some legacy release that sole depends on rebar?
* You do not like rebar3?

E.g. I've migrated to `rebar3` few years ago. I do not think that any new development goes with old rebar?

**Comment by silviucpp** [comment]
Hello,

I have few ancient projects that are using NIFS which requires more work to migrate to rebar3, also they are using some old code for deployment that depends on rebar and last time when I tried to migrate I found this bug : https://github.com/erlware/relx/issues/511 :)) was marked as fixed but I see also commits in June this year on this bug even if I reported in 2016 :).

**Comment by fogfish** [comment]
I see, that you for clarification. This was my guess as well (about ancient projects). I'll bring the support for `rebar` but you would need to help me with testing. I would introduce this feature in separate branch first. Once, You'll confirm that it works I'll merge it to `master`.

I hope you are fine with this!

**Comment by fogfish** [comment]
Please test PR #12. I'll merge it once you confirm it.

**Comment by silviucpp** [comment]
Working fine
