### ISSUE TITLE
Can you make a new release and push the library to hex.pm as well ?

### ISSUE THREAD

**Issue by silviucpp** [fogfish/esq#13]
Hello,

I'm using your project in one of my public projects: https://github.com/silviucpp/erlkaf
More and more peoples are using hex.pm with rebar3 but in order to submit there all deps needs to support this.

Do you have any plans to submit your lib ?

Also can you tag a new release ?

Silviu

**Comment by fogfish** [comment]
This sounds as a good idea! I had an idea to publish it to hex. Unfortunately, I need to mitigate deps to one of my library `feta`. I'll try to find a work around... I'll let you know when this feature is complete. It should take me few days.

**Comment by fogfish** [comment]
A quick update here. I can eliminate dependencies to `feta` library and publish `uid` to hex. I would be ready be next week Tue.

**Comment by silviucpp** [comment]
Thanks for update,

Silviu

**Comment by fogfish** [comment]
PR #14 should deliver enablers for this feature request. I still need to run a few tests in order to ensure that library is stable before I'll merge it. After that I'll be able to publish this lib to hex. 

Please feel free to test branch `deps-via-hex` with you application to ensure that it works.

**Comment by fogfish** [comment]
Now, it is available via hex. Feel free to raise any issues.

**Comment by fogfish** [comment]
Just out of curiosity... Have you used this feature in your app?

**Comment by silviucpp** [comment]
Hello, 

Sorry not yet ! I'm using you library in multiple projects and I upgraded to lat release but via rebar3 and rebar only

Silviu
