### ISSUE TITLE
Add head function to focus on first queue element.

### ISSUE THREAD

**Issue by fogfish** [fogfish/esq#2]
```erlang
-spec head(#q{}) -> _ | undefined.
```

**Comment by silviucpp** [comment]
Any idea when we can have this functionality implemented ?

Thanks,
Silviu

**Comment by fogfish** [comment]
I thought about it. The implementation require #3. I might procedure with it during next week only.

**Comment by silviucpp** [comment]
Ok thanks a lot ! I'll watch this 2 issues for the progress

**Comment by fogfish** [comment]
about one week...

**Comment by fogfish** [comment]
See latest master branch. If you need a previous version see tag `1.0.1`.
