### ISSUE TITLE
How to build locally with otp-25?

### ISSUE THREAD

**Issue by aerosol** [fogfish/esq#22]
Hi,

I wanted to give this a go locally, but I'm unable to build it with the recent otp.
I haven't been following erlang too closely lately; do you perhaps know if there's a quick fix for the following error?

Thanks!

```
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
```

```
12:33:32 carb ~/dev/esq
master $ make
==> install rebar (3.20.0)
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling datum
===> Compiling _build/default/lib/datum/src/maplike/heap.erl failed
_build/default/lib/datum/src/maplike/heap.erl:69:2: type heap() is unused
_build/default/lib/datum/src/maplike/heap.erl:72:2: type rank() is unused

make: *** [erlang.mk:84: compile] Error 1
```

**Comment by aerosol** [comment]
FWIW I've tried adding the no warnings switch at the top-level rebar.conf, but no dice still

```
{erl_opts, [
   warnings_as_errors
]}.
```

**Comment by ioolkos** [comment]
@aerosol Maybe OTP 25 does more checking on unused types. You can always take away the `warning_as_errors` from datum.
You could append an override to the `esq` rebar.conf file, to allow it to compile:

```
{overrides,
    [{override, datum, [{erl_opts, [{platform_define, "^17.", 'OTP_17'}]}]}]
}.
```

**Comment by aerosol** [comment]
Perfect, thanks @fogfish. The override did the trick, tests seem to be running fine.
